name: Build and push the tagged build to production
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extractTag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4.1.1

      - id: extractTag
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${{ steps.extractTag.outputs.tag }}
          push: true
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
        id-token: write
        contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          # Version of helm
          version: v3.3.1
      - name: Azure Login
        uses: Azure/login@v1.5.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with:
          # Specify the script here
          inlineScript: |
            az ad app federated-credential update \
              --federated-credential-id PROD_CRED \
              --id ${{ secrets.AZURE_CLIENT_ID }} 
              --parameters "{
                  "name": "PROD_CRED",
                  "issuer": "https://token.actions.githubusercontent.com",
                  "subject": "repo:zevanreg/mslearn-aks-deployment-pipeline-github-actions:ref:refs/tags/${{ needs.build.outputs.tag }}",
                  "description": "Testing",
                  "audiences": [
                      "api://AzureADTokenExchange"
                  ]
                }"
      
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace production \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }}
            --set image.tag=${{ needs.build.outputs.tag }}
